# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Environment variables
env:
  global:
    - GH_REPO_NAME: Nebula
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/Bwar/Nebula.git

# safelist
branches:
  only:
  - gh-pages

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
     branch: gh-pages

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generate_docs.sh
  - ./generate_docs.sh

