language: C++

# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Environment variables
env:
  global:
    - GH_REPO_NAME: Nebula
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/Bwar/Nebula.git

# blocklist
branches:
  except:
  - develop

# safelist
branches:
  only:
  - master
  - gh-pages

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: gh-pages

before_install:
    - sudo apt-get install python-software-properties 
    - sudo apt-add-repository -y ppa:libreoffice/libreoffice-4-2
    - sudo apt-get update
    - sudo apt-get install doxygen

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
docs:
  - doxygen Doxyfile
# - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generate_docs.sh
  - ./generate_docs.sh

